### ISSUE TITLE
Using

### ISSUE THREAD

**Issue by wmwart** [andrico1234/ra-access-control-lists#1]
Thanks for the reply to the post [https://github.com/marmelab/react-admin/issues/5933#issuecomment-812836396](https://github.com/marmelab/react-admin/issues/5933#issuecomment-812836396)

There are a lot of libraries for managing a access, and everyone can find something that suits his project or writes his own.

For my projects, I use and recommend [https://github.com/stalniy/casl](https://github.com/stalniy/casl). It is great for all use cases. In addition, I use the same library both on the front-end and on the back-end.

What about your suggestion: it doesn't solve my problem - over-cluttered code. As each field was wrapped in an access wrapper, it will remain with your solution. The only way out I see is injecting access handlers directly into react-admin components

**Comment by andrico1234** [comment]
Hi @wmwart, thanks for opening up the issue. Do you have an ideal API for your RA components?

The fields for `ra-acl` look like this

```
<FieldWithPermission Input={CustomField} inputProps={{}} source="" label="" />
```

But you can also wrap your own using `useAcl` without directly managing permission logic in your form components.

How would you expect to manage permission in RA?
